name: Publish fast-graphrag to AWS ECR.
on:
  push:

jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Poetry
        run: pipx install poetry==1.8.*

      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Build the package
        run: poetry build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Push to ECR
        run: |
          chmod +x ./bin/push_to_ecr.sh
          ./bin/push_to_ecr.sh cap-fast-graphrag . cap-fast-graphrag latest Dockerfile